# -*- coding: utf-8 -*-
"""
Created on Thu Aug 13 23:32:47 2026

@author: pabda
"""

# Standard Libraries
import pandas as pd
import numpy as np
import yfinance as yf
import time
import mplfinance as mpf

# Custom Libraries
...


# Strategy Class
class Strategy2:
    
    """ 
    Strategy 2: SuperTrend Strategy
        
        Description:
            
            A strategy that uses the SuperTrend indicator to identify buy and sell signals
            based on the predominant direction of the market trend.
        
    Strategy For:
        
        - Stocks
        - Indices
        - ETFs
        - Currencies
        - Commodities
        - Cryptocurrencies
        
    Frequencies (Time Frames):
        
        - Intraday
        - Daily
        - Weekly
        - Monthly
        
    Holding Period:
        
        - Variable (Depends on trend strength)
        
    Analysis Used: 
        
        - Technical Analysis
            * SuperTrend
    
    Detailed Strategy Description:    
        
        A strategy that uses the SuperTrend indicator to determine the direction of the predominant market trend.
        A buy signal is considered when the price crosses above the SuperTrend line (indicating a bullish trend),
        and a sell signal is considered when the price crosses below the SuperTrend line (indicating a bearish trend).
                        
        Stop Loss and Take Profit Description:
            
            Take Profit:
                
                Profit-taking is triggered when a signal opposite to the current position occurs.
                
            Stop Loss:
                
                Loss limitation occurs when a signal opposite to the current position occurs.
                
    General Assumptions:
        
        - This strategy does not account for costs or commissions (opening fees, rollovers, among others).
        
        - In high-volatility situations, such as news events or quarterly earnings reports that significantly
          affect the price (for stocks), the SuperTrend indicator may generate false signals due to sudden
          and temporary market movements.
        
    Notes:
        
        - Remember that the lines drawn on the chart not only indicate the current market trend, but may also
          function as support or resistance levels, providing additional information for trading decisions.
    """
    
    __version__ = 1.0
    
    
    # __init__
    def __init__(self, df: pd.DataFrame, length: int = 14, factor: float = 3.0) -> None:
        
        """
        Constructor.
        
        Parameters
        ----------
        param : pd.DataFrame : df : Historical data of the financial asset.
        ----------
        param : int : length : Window used in the ATR for the ST calculation (default is 14).
        ----------
        param : float : factor : Calculation multiplier for the ATR (default is 3.0).
        
        Output
        -------
        return: NoneType : None
        """
        
        # Attributes
        self.df = df
        self.length = length
        self.factor = factor
        self.strategy_calculation = None
        
        # Private Attributes
        
    
    # __repr__
    def __repr__(self) -> str:
        return self.__class__.__name__ + ".class"
    
    
    # Backtest
    def backtest(self) -> pd.DataFrame:
        
        """
        This method obtains the return generated by the SuperTrend strategy.
        
        Output
        -------
        return: pd.DataFrame : Strategy return over time.
        """
        
        # Calculate
        if self.strategy_calculation is None:
            self.calculate()
            
        data = self.strategy_calculation.copy()
        trend = np.where(data["FinalLowerB"].notna(), 1, -1)
        data["Trend"] = trend
        
        # Calculate return
        data["Return"] = self.df["Close"].pct_change()
        returns = (1 + data["Trend"].shift(periods=1) * data["Return"]).cumprod()
        
        return returns
    
    
    # Calculate
    def calculate(self) -> dict:
        
        """
        This method calculates the SuperTrend indicator from the historical data
        that was provided as a parameter.
        
        Output
        -------
        return: dict|bool : Returns a dictionary if a signal was generated on the last candle,
                           or False if no signal was generated.
        """
        
        # Calculate True Range (TR)
        High, Low = self.df["High"], self.df["Low"]
        H_minus_L = High - Low
        prev_close = self.df["Close"].shift(periods=1)
        H_minus_PC = abs(High - prev_close)
        L_minus_PC = abs(Low - prev_close)
        TR = pd.Series(np.max([H_minus_L, H_minus_PC, L_minus_PC], axis=0),
                       index=self.df.index, name="TR")
        
        # Calculate ATR (Average True Range)
        ATR = TR.ewm(alpha=1 / self.length).mean()
        
        # Calculate basic values
        middle = ((High + Low) / 2)
        FinalUpperB = middle + self.factor * ATR
        FinalLowerB = middle - self.factor * ATR
        
        # Initialize SuperTrend
        SuperTrend = np.zeros(ATR.shape[0])
        close = self.df["Close"]
        
        for i in range(1, ATR.shape[0]):
            
            # Calculate SuperTrend for each point
            if close.iloc[i] > FinalUpperB.iloc[i - 1]:
                SuperTrend[i] = True
                
            elif close.iloc[i] < FinalLowerB.iloc[i - 1]:
                SuperTrend[i] = False
                
            # The trend continues
            else:
                SuperTrend[i] = SuperTrend[i - 1]
                
                # Adjust final bands
                if SuperTrend[i] == True and FinalLowerB.iloc[i] < FinalLowerB.iloc[i - 1]:
                    FinalLowerB.iloc[i] = FinalLowerB.iloc[i - 1]
                    
                elif SuperTrend[i] == False and FinalUpperB.iloc[i] > FinalUpperB.iloc[i - 1]:
                    FinalUpperB.iloc[i] = FinalUpperB.iloc[i - 1]
                    
            # Remove bands according to trend direction
            if SuperTrend[i] == True:
                FinalUpperB.iloc[i] = np.nan
                
            else:
                FinalLowerB.iloc[i] = np.nan
                
        # Adjust initial value at position 0
        if SuperTrend[1] == 0:
            FinalLowerB.iloc[0] = np.nan
            
        else:
            FinalUpperB.iloc[0] = np.nan
            
        # Remove unwanted values
        FU = FinalUpperB.iloc[self.length - 1:]
        FL = FinalLowerB.iloc[self.length - 1:]
        ST_df = pd.concat([FU, FL], axis=1)
        ST_array = np.nansum([FU, FL], axis=0)
        ST_array[0] = np.nan
        ST_df["SuperTrend"] = ST_array
        ST_df.columns = ["FinalUpperB", "FinalLowerB", "SuperTrend"]
        
        # Save calculation as an attribute
        self.strategy_calculation = ST_df
        
        # Check if a signal was generated
        if pd.isna(ST_df["FinalUpperB"].iloc[-2]) & pd.notna(ST_df["FinalUpperB"].iloc[-1]): # New Bearish Trend
            value = {"Trend": "Bearish"}
            
        elif pd.isna(ST_df["FinalLowerB"].iloc[-2]) & pd.notna(ST_df["FinalLowerB"].iloc[-1]): # New Bullish Trend
            value = {"Trend": "Bullish"}
            
        else:
            value = False

        return value
    
    
    # Optimize
    def optimize(self, period_range: list, factor_range: list) -> pd.DataFrame:
        
        """
        This method optimizes the strategy parameters to maximize profitability.
        
        Parameters
        ----------
        param : list : period_range : Lower and upper limits of the length.
        ----------
        param : list : factor_range : Lower and upper limits of the factors.
        
        Output
        -------
        return: pd.DataFrame : Returns for each strategy that has been tested.
        """
        
        # Optimize
        combinations = []
        
        for l in range(period_range[0], period_range[1] + 1):
            for r in range(factor_range[0], factor_range[1] + 1):
                combinations.append([l, r])
                
        # Save initial values
        length = self.length
        factor = self.factor
        
        # Test combinations
        returns = []
        
        for length_value, factor_value in combinations:
            
            # Modify values to calculate the strategy
            self.length = length_value
            self.factor = factor_value
            
            # Calculate strategy with updated values
            self.calculate()
            
            # Backtest
            strategy_return = self.backtest()
            
            # Add return and parameters
            returns.append([length_value, factor_value, strategy_return.iloc[-1]])
            
        # Convert into a DataFrame
        returns = pd.DataFrame(data=returns,
                               columns=["Length", "Factor", "Total Return"])
        
        # Sort based on returns (highest to lowest)
        returns = returns.sort_values(by="Total Return", ascending=False)

        # Restore original values
        self.length = length
        self.factor = factor
        self.calculate()
        
        return returns
    
    
    # Plot
    def plot(self, path: str = "Strategy2_SuperTrend.png") -> None:
        
        """
        This method creates a graphical representation of our data together with our indicator.
        
        Parameters
        ----------
        param : str : path : Path where the plot will be saved
                             (default is "Strategy2_SuperTrend.png").
        
        Output
        -------
        return: NoneType : None.
        """
        
        # Plot
        sp_plots = [
            
            mpf.make_addplot(self.strategy_calculation["SuperTrend"],
                             label="Trend Change", color="black"),
            
            mpf.make_addplot(self.strategy_calculation["FinalUpperB"],
                             label="Bearish Trend", color="red"),
            
            mpf.make_addplot(self.strategy_calculation["FinalLowerB"],
                             label="Bullish Trend", color="green")
            
            ]
        
        mpf.plot(self.df.loc[self.strategy_calculation.index],
                 type="candle",
                 style="yahoo",
                 volume=True,
                 figsize=(22, 12),
                 title=dict(title="Strategy 2 Chart - SuperTrend",
                            fontsize=20, y=0, x=0.55),
                 ylabel="Price",
                 ylabel_lower="Volume",
                 savefig=path,
                 addplot=sp_plots,
                 figscale=3.0,
                 tight_layout=True,
                 warn_too_much_data=self.df.loc[self.strategy_calculation.index].shape[0])


if __name__ == "__main__":
    
    # Getting data
    start_date = "2021-01-01"
    end_date = "2024-01-01"
    ticker = "AMZN"
    df = yf.download(ticker, start=start_date, end=end_date, interval="1d")
    
    # Fixing yfinance MultiIndex
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    
    # Initialize strategy
    st2 = Strategy2(df=df, length=14, factor=3.0)
    
    # Calculate
    calculation = st2.calculate()
    print(calculation)
    
    # Example of a signal
    print(Strategy2(df=df.loc[:"2023-10-30"],
                    length=14,
                    factor=3.0).calculate())
    
    # Backtest
    backtest = st2.backtest()
    print("Final Return with Current Parameters:", backtest.iloc[-1])
    
    # Optimize
    length_range = [5, 100]
    factor_range = [1, 5]
    start = time.time()
    
    returns = st2.optimize(period_range=length_range,
                           factor_range=factor_range)
    
    print(returns)
    print("It took {} seconds".format(time.time() - start))
    
    # Fit best parameters
    st2 = Strategy2(df=df,
                    length=int(returns.iloc[0, 0]),
                    factor=int(returns.iloc[0, 1]))
    
    st2.calculate()
    
    # Backtest
    backtest = st2.backtest()
    print("Final Return with Current Parameters:", backtest.iloc[-1])
    
    # Save plot
    st2.plot()